/** @format */

import Head from "next/head";
import React, { useState } from "react";
import { useRouter } from "next/router";
import Cookies from "universal-cookie";
import axios from "axios";

const cookies = new Cookies();

const initialState = {
	fullName: "",
	password: "",
};

export default function SignIn() {
    const [form, setForm] = useState(initialState);
		const router = useRouter();
		const handleChange = (e: any) => {
			setForm({ ...form, [e.target.name]: e.target.value });
		};
	return (
		<>
			<Head>
				<title>Sign in to Nkata: Flexible Web-based Chat Application</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="auth__form-container">
				<div className="auth__form-container_fields">
					<div className="auth__form-container_fields-content">
						<p>Nkata-Sign In</p>
						<form>
							<div className="auth__form-container_fields-content_input">
								<label htmlFor="username">Username</label>
								<input
									name="username"
									type="text"
									placeholder="Username"
									onChange={handleChange}
									required
								/>
							</div>

							<div className="auth__form-container_fields-content_input">
								<label htmlFor="password">Password</label>
								<input
									name="password"
									type="password"
									placeholder="Password"
									onChange={handleChange}
									required
								/>
							</div>

							<div className="auth__form-container_fields-content_button">
								<button type="submit">Sign In</button>
							</div>
						</form>
						<div className="auth__form-container_fields-account">
							<p>
								Don't have an account?
								<span onClick={() => router.push("/signup")}>Sign Up</span>
							</p>
						</div>
					</div>
				</div>
				<div className="auth__form-container_image">
					<img src="/assets/landingimage.jpg" alt="sign-in" />
				</div>
			</div>
		</>
	);
}
